package:
  name: sympy-release
  version: 2.0

requirements:
  run:
    # Also requires vagrant, but there isn't a conda package for that yet.
    - python
    - fabric
    - fabric-virtualenv
    - requests
    - requests-oauthlib
    - ipython

about:
  license: BSD
  summary: "All the things needed to make a release of SymPy."
